influxdb: "localhost:8086"
logstash: "localhost:12201"
chat: "localhost:4245"
rabbitmq: "localhost:5672"
grpc_flights: "localhost:4242"
grpc_trains: "localhost:4243"
revoker: "localhost:8081"
fake_api: "localhost:8000"
