{
 "title": "KrakenD AI Gateway",
 "description": "Official Grafana dashboard for KrakenD AI LLM metrics. Feeds from Prometheus using PromQL queries.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "label": "Application", "query": { "query": "label_values(app)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "provider", "label": "LLM provider", "query": { "query": "label_values(provider)" } },
   { "name": "interval", "label": "Interval", "query": "1m,5m,15m,30m,1h,2h,1d" }
  ]
 },
 "panels": [
  { "title": "Tokens $provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "provider" },
  {
   "title": "Total tokens",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "krakend_llm_tokens_total{provider=~\"$provider\", app=~\"$app\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total IN tokens",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "krakend_llm_tokens_in_total{provider=~\"$provider\", app=~\"$app\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total OUT tokens",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "krakend_llm_tokens_out_total{provider=~\"$provider\", app=~\"$app\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(krakend_llm_tokens_total{provider=~\"$provider\", app=~\"$app\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total IN tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "increase(krakend_llm_tokens_in_total{provider=~\"$provider\", app=~\"$app\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total OUT tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "increase(krakend_llm_tokens_out_total{provider=~\"$provider\", app=~\"$app\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}